packages: [ ]

catalogs:
  build:
    "@intlify/unplugin-vue-i18n": ^11.0.1
    "@shikijs/markdown-it": ^3.19.0
    "@unocss/eslint-config": ^66.5.10
    "@vitejs/plugin-vue": ^6.0.2
    beasties: ^0.3.5
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.53.3
    shiki: ^3.19.0
    unocss: ^66.5.10
    unplugin: ^2.3.11
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.18.0
    vite: ^7.2.6
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-pwa: ^1.2.0
    vite-plugin-vue-devtools: ^8.0.5
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.2.2
    vite-ssg-sitemap: ^0.10.0

  dev:
    "@antfu/eslint-config": ^6.3.0
    "@iconify-json/carbon": ^1.2.14
    "@vue-macros/volar": ^3.1.1
    "@vue/test-utils": ^2.4.6
    cypress: ^15.7.1
    cypress-vite: ^1.8.0
    eslint: ^9.39.1
    eslint-plugin-cypress: ^5.2.0
    eslint-plugin-format: ^1.0.2
    https-localhost: ^4.7.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vitest: ^4.0.15
    vue-tsc: ^3.1.5

  frontend:
    "@unhead/vue": ^2.0.19
    "@unocss/reset": ^66.5.10
    "@vueuse/core": ^14.1.0
    nprogress: ^0.2.0
    pinia: ^3.0.4
    vue: ^3.5.25
    vue-i18n: ^11.2.2
    vue-router: ^4.6.3

  types:
    "@types/markdown-it-link-attributes": ^3.0.5
    "@types/nprogress": ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
