/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		FiguresComponent: typeof import("./components/FiguresComponent.vue")["default"];
		MapComponent: typeof import("./components/MapComponent.vue")["default"];
		README: typeof import("./components/README.md")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		TheFooter: typeof import("./components/TheFooter.vue")["default"];
		TheHeader: typeof import("./components/TheHeader.vue")["default"];
	}
}
